server {
    listen 80;

    location / {
        proxy_pass http://frontend:80;
    }

    location /api/ {
        proxy_pass http://backend:8000/;
    }

    location /openapi.json {
        proxy_pass http://backend:8000/openapi.json;
    }

    location /docs {
        proxy_pass http://backend:8000/docs;
    }
}
