server {
    listen 80;
    server_name task-manager-higzi.ru www.task-manager-higzi.ru;

    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    server_name task-manager-higzi.ru www.task-manager-higzi.ru;

    ssl_certificate /etc/letsencrypt/live/task-manager-higzi.ru/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/task-manager-higzi.ru/privkey.pem;

    location / {
        proxy_pass http://frontend:80;
    }

    location /api/ {
        proxy_pass http://backend:8000/;
    }

    location /openapi.json {
        proxy_pass http://backend:8000/openapi.json;
    }

    location /docs {
        proxy_pass http://backend:8000/docs;
    }
}
